-- AUTO COMM enterprise schema blueprint. Review and adapt to the existing Supabase Pro schema before production migration.

create table if not exists brands (id uuid primary key default gen_random_uuid(), name text not null unique, role text not null, created_at timestamptz default now());
create table if not exists locations (id uuid primary key default gen_random_uuid(), brand_id uuid references brands(id), name text not null, city text, state text, service_radius_miles integer, whatsapp_routing_label text, active boolean default true, created_at timestamptz default now());
create table if not exists contacts (id uuid primary key default gen_random_uuid(), first_name text, last_name text, company text, phone_e164 text unique, email text, city text, state text, source text, consent_status text not null, lifecycle_stage text default 'new', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists consent_events (id uuid primary key default gen_random_uuid(), contact_id uuid references contacts(id), channel text not null, event_type text not null, evidence text, created_at timestamptz default now());
create table if not exists campaigns (id uuid primary key default gen_random_uuid(), name text not null, brand_id uuid references brands(id), audience text, channel text not null, status text default 'draft', approval_status text default 'needs_review', created_at timestamptz default now());
create table if not exists conversations (id uuid primary key default gen_random_uuid(), contact_id uuid references contacts(id), channel text not null, status text default 'open', assigned_brand_id uuid references brands(id), assigned_location_id uuid references locations(id), last_message_at timestamptz, created_at timestamptz default now());
create table if not exists messages (id uuid primary key default gen_random_uuid(), conversation_id uuid references conversations(id), direction text not null, body text, template_name text, provider_message_id text, ai_generated boolean default false, created_at timestamptz default now());
create table if not exists lead_scores (id uuid primary key default gen_random_uuid(), contact_id uuid references contacts(id), score numeric not null, intent text, rationale text, created_at timestamptz default now());
create table if not exists handoff_tasks (id uuid primary key default gen_random_uuid(), contact_id uuid references contacts(id), conversation_id uuid references conversations(id), priority text, reason text, owner text, status text default 'open', created_at timestamptz default now());
create table if not exists audit_events (id uuid primary key default gen_random_uuid(), actor text not null, action text not null, target text, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
